name: Deploy Lambda Function

on:
  push:
    paths:
      - src/ec2_control.py
      - terraform/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Python Code with Ruff
      run: |
        pip install ruff
        ruff check src --config .ruff.toml  # Ensure Ruff uses the config file

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init -backend-config=backend.tfvars
      working-directory: terraform

    - name: Lint Terraform Code
      run: |
        terraform fmt -check
        terraform validate
      working-directory: terraform

    - name: Run packaging script
      run: |
        chmod +x scripts/package_lambda.sh
        bash scripts/package_lambda.sh

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform